baseURL = 'https://mollycarroll.dev/'
languageCode = 'en-us'
title = "Molly Carroll's software engineering shenanigans | peace. love. AI."
copyright = 'Molly Carroll'                                                   # Used in the footer copyright mention.
enableRobotsTXT = true

[module]
[[module.imports]]
path = "github.com/michenriksen/hugo-theme-til"

[outputs]
home = ['html']
section = ['html', 'rss', 'json']
page = ['html']

[menus]
[[menus.main]]
name = 'Notes'
pageRef = '/notes'
weight = 20
[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 30
[[menus.main]]
name = 'Graph'
pageRef = '/graph'
weight = 40

[markup]
[markup.highlight]
noClasses = false
style = 'monokai'

[markup.goldmark]
[markup.goldmark.parser]
[markup.goldmark.parser.attribute]
block = true
